<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // SMARTFÓNY - SÉRIA 1
            [
                'id' => 1,
                'title' => 'iPhone 15 Pro',
                'brand' => 'Apple',
                'price' => 999.00,
                'oldPrice' => 1099.00,
                'image' => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=940&hei=1112&fmt=png-alpha&.v=1692845702708',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 10,
                'monthlyPrice' => '24,95',
                'description' => 'The iPhone 15 Pro is forged in titanium and features the groundbreaking A17 Pro chip, a customizable Action button, and a more versatile Pro camera system.',
                'specs' => [
                    'Display' => '6.1" Super Retina XDR, ProMotion',
                    'Processor' => 'A17 Pro chip',
                    'RAM' => '8GB',
                    'Storage' => '128GB, 256GB, 512GB, 1TB',
                    'Camera' => '48MP Main, 12MP Ultra Wide, 12MP 3x Telephoto',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'TOP 1',
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 2,
                'title' => 'Samsung Galaxy S24 Ultra',
                'brand' => 'Samsung',
                'price' => 1299.99,
                'oldPrice' => 1399.99,
                'image' => 'https://images.unsplash.com/photo-1610945264803-c22b62d2a7b6?w=600&q=80&auto=format&fit=crop',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 8,
                'monthlyPrice' => '32,50',
                'description' => 'Ultimate Galaxy smartphone with a new titanium exterior, 6.8" flat display, and Galaxy AI features for enhanced creativity and productivity.',
                'specs' => [
                    'Display' => '6.8" Dynamic AMOLED 2X, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 3 for Galaxy',
                    'RAM' => '12GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '200MP Main, 50MP 5x Zoom, 12MP Ultra-Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 7
            ],
            [
                'id' => 3,
                'title' => 'Google Pixel 8 Pro',
                'brand' => 'Google',
                'price' => 999.00,
                'oldPrice' => 1099.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcS8dvAb4N9RhGWin5sw9MudR4H_l4tygeHSXCosvHDaOeKSu8aE0jKhMe4Fi6vfKmCSi1R6_ps7ZEmImiEpx30WXsQ3YgeoPdrGXi9KI3_ryQM7s7q4O9s0kpRvorSiCXEwUmbFRX4pog&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 15,
                'monthlyPrice' => '24,95',
                'description' => 'The most powerful Pixel yet, with Google AI, a pro-level triple camera system, and a custom-built Google Tensor G3 chip.',
                'specs' => [
                    'Display' => '6.7" Super Actua LTPO OLED',
                    'Processor' => 'Google Tensor G3',
                    'RAM' => '12GB',
                    'Storage' => '128GB, 256GB, 512GB, 1TB',
                    'Camera' => '50MP Main, 48MP Ultra-Wide, 48MP 5x Telephoto',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 4,
                'title' => 'Xiaomi 14 Pro',
                'brand' => 'Xiaomi',
                'price' => 799.00,
                'oldPrice' => 899.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTNObkdlb8r0N36mYOiInisVRTEXCKgVGybIRgOojT6YOSk4GS1b8PLs9W1zavAkjHpeJZvHTryDEcGMjv5YenlATrrAsBO-dgOr7AVekQ0268St53y0NBd4w&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 20,
                'monthlyPrice' => '19,95',
                'description' => 'Featuring a legendary Leica Summilux optical lens, Snapdragon 8 Gen 3 processor, and all-new HyperOS.',
                'specs' => [
                    'Display' => '6.73" LTPO AMOLED, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'RAM' => '12GB, 16GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '50MP Main, 50MP Telephoto, 50MP Ultra-Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 5,
                'title' => 'OnePlus 12',
                'brand' => 'OnePlus',
                'price' => 799.00,
                'oldPrice' => 899.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ3VS7KY6yFPun5RvJ0NTzdcrQclJjt7uGGqy-I0DkfLshm4lLu4cSR6DBoZaUDj03DRjmKE1S1ACVmHikgBhCbkcrOyQzkdLfsJdnp4i4umP3uB21DOBeNWrGpeWvU&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 12,
                'monthlyPrice' => '19,95',
                'description' => 'Fast and smooth redefined with Snapdragon 8 Gen 3, a stunning 120Hz ProXDR display, and Hasselblad camera system.',
                'specs' => [
                    'Display' => '6.82" LTPO AMOLED, 120Hz ProXDR',
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'RAM' => '12GB, 16GB, 24GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '50MP Main, 48MP Ultra-Wide, 64MP Periscope',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 6,
                'title' => 'iPhone 14',
                'brand' => 'Apple',
                'price' => 699.00,
                'oldPrice' => 799.00,
                'image' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQr4OteYxq-5uyqvadd1Vb-WOyVokE6mxVPp72FZ37Pe9Ls62Gc_Z5s7bfdf6CX8SIxkWsXZfjYaTA2ZfCt4NPWoA5Ib25riXl4VkLmiJwHMf_-_7ak--L6fWzpwy7tH7qvnwyrYB0&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 25,
                'monthlyPrice' => '17,45',
                'description' => 'Durable design, impressive dual-camera system, and groundbreaking safety features like Crash Detection.',
                'specs' => [
                    'Display' => '6.1" Super Retina XDR',
                    'Processor' => 'A15 Bionic chip',
                    'RAM' => '6GB',
                    'Storage' => '128GB, 256GB, 512GB',
                    'Camera' => '12MP Main, 12MP Ultra Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 7,
                'title' => 'Samsung Galaxy A54',
                'brand' => 'Samsung',
                'price' => 349.00,
                'oldPrice' => 449.00,
                'image' => '',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 30,
                'monthlyPrice' => '8,70',
                'description' => 'Vibrant Super AMOLED display, versatile triple camera system, and long-lasting battery for everyday use.',
                'specs' => [
                    'Display' => '6.4" Super AMOLED, 120Hz',
                    'Processor' => 'Exynos 1380',
                    'RAM' => '6GB, 8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '50MP Main, 12MP Ultra Wide, 5MP Macro',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 22
            ],

            // TABLETY
            [
                'id' => 8,
                'title' => 'iPad Pro 13" M4',
                'brand' => 'Apple',
                'price' => 1299.00,
                'oldPrice' => 1499.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSH7pIFGVBGoyfv1yiFxiTBpkuXoQX35W0Xok0cgthlaQoDtukttyrwtyYPxSiaUXsaOm6GgYyM1zh4Rs3WVY2QC7_AjK7QKCWFP2ekkMOXP8N_EyfLzYk-3jgaTIHCWOyMZqZZwIWGkHQ&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 8,
                'monthlyPrice' => '32,45',
                'description' => 'Incredibly thin and light, featuring the breakthrough Ultra Retina XDR Tandem OLED display and blazing-fast M4 performance.',
                'specs' => [
                    'Display' => '13" Ultra Retina XDR (Tandem OLED)',
                    'Processor' => 'Apple M4 chip',
                    'RAM' => '8GB, 16GB',
                    'Storage' => '256GB, 512GB, 1TB, 2TB',
                    'Camera' => '12MP Wide, LiDAR Scanner',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'TOP 2',
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 9,
                'title' => 'Samsung Galaxy Tab S9 Ultra',
                'brand' => 'Samsung',
                'price' => 1099.00,
                'oldPrice' => 1299.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRcRfUJTk6pFfyfmIegdKhZ6AuuNy5w832SLcDMzYdh35glAB5V70_NEXfYjPG289jgbAVg4JPBnag0Dc-g1isDdWg7mjLy',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 10,
                'monthlyPrice' => '27,45',
                'description' => 'Massive 14.6" Dynamic AMOLED 2X display, Snapdragon 8 Gen 2 for Galaxy, and included S Pen for work and play.',
                'specs' => [
                    'Display' => '14.6" Dynamic AMOLED 2X, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 2 for Galaxy',
                    'RAM' => '12GB, 16GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '13MP Main, 8MP Ultra-Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 10,
                'title' => 'iPad Air 11" M2',
                'brand' => 'Apple',
                'price' => 599.00,
                'oldPrice' => 699.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQl7G0z6kxc50hSQ7tU9qHZvU-_4Yf4rckivNUNbY8wpIr9ss2ztozY6oTQgICtNul1LELv1L_Dj-lS8R7P3F6smrx-21qRfr6-VGfOsVpu8_tcBBij05cMDjSU',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 15,
                'monthlyPrice' => '14,95',
                'description' => 'Incredible performance and advanced features in a thin and light design with the powerful M2 chip.',
                'specs' => [
                    'Display' => '11" Liquid Retina',
                    'Processor' => 'Apple M2 chip',
                    'RAM' => '8GB',
                    'Storage' => '128GB, 256GB, 512GB, 1TB',
                    'Camera' => '12MP Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 11,
                'title' => 'Samsung Galaxy Tab S9',
                'brand' => 'Samsung',
                'price' => 799.00,
                'oldPrice' => 899.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSTgAYfogFLNL_t_wvG-J4PWli37-CyFNqD7RoZvAnt6Y6NgpYRSAHn3LEZIzX_yULXJcIrZ-iHl38agPFGzLOwrPnN-tXdGMA4jVRCdoxjSOsKv8_On2z-fFs4',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 12,
                'monthlyPrice' => '19,95',
                'description' => 'Stunning 11" Dynamic AMOLED 2X display, powerful performance, and IP68 water and dust resistance.',
                'specs' => [
                    'Display' => '11" Dynamic AMOLED 2X, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 2 for Galaxy',
                    'RAM' => '8GB, 12GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '13MP Main',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 12,
                'title' => 'Lenovo Tab P12',
                'brand' => 'Lenovo',
                'price' => 329.00,
                'oldPrice' => 379.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQb3aXDVc0ZxIEcpFRytbNIJKzWd2_11aJAsehausYiuYI-Pv_np3FOZz6O5cJeiSXuj-OwUtcrPSLD_q13VCn_bUrE95hn7R_FtSRndPwbBLwASmeC9xoVOw',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 18,
                'monthlyPrice' => '8,20',
                'description' => 'Versatile tablet for entertainment and productivity, featuring a large 12.7" 3K display and quad JBL speakers.',
                'specs' => [
                    'Display' => '12.7" 3K LCD',
                    'Processor' => 'MediaTek Dimensity 7050',
                    'RAM' => '4GB, 8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '8MP Rear, 13MP Front',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 13,
                'title' => 'iPad 10.9" (2022)',
                'brand' => 'Apple',
                'price' => 399.00,
                'oldPrice' => 449.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQXipsRyYabvbp6B_EGjc7AwpKnU3-_PBhyxa0EWxX_1WddiKJPS6b7VwlnC_gXXxYvircqDSULldU1lpRiNVdmsawRgNwkanPm7jv_2Iz3Rvpte_G0LBvFGg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 20,
                'monthlyPrice' => '9,95',
                'description' => 'All-screen design with a 10.9" Liquid Retina display, powered by the A14 Bionic chip for everyday tasks.',
                'specs' => [
                    'Display' => '10.9" Liquid Retina',
                    'Processor' => 'A14 Bionic chip',
                    'RAM' => '4GB',
                    'Storage' => '64GB, 256GB',
                    'Camera' => '12MP Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 14,
                'title' => 'Xiaomi Pad 6',
                'brand' => 'Xiaomi',
                'price' => 299.00,
                'oldPrice' => 349.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTYu3MMxNFNOqWltvLfg48CE0EVh9woUevBbB1bAziQsjWWzA_K56pdi52oiWb-z1GKgGZX7xs79o9IaqDF5OQ-3gB4RExsp6-1Ej_coxv7jBFiAoy0V6Iazg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 25,
                'monthlyPrice' => '7,45',
                'description' => 'Immersive 11" 2.8K 144Hz display and powerful Snapdragon 870 processor in a sleek metal design.',
                'specs' => [
                    'Display' => '11" 2.8K LCD, 144Hz',
                    'Processor' => 'Snapdragon 870',
                    'RAM' => '6GB, 8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '13MP Rear, 8MP Front',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],

            // NOTEBOOKY
            [
                'id' => 15,
                'title' => 'MacBook Pro 16" M3 Max',
                'brand' => 'Apple',
                'price' => 3499.00,
                'oldPrice' => 3999.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTI7esxi_DL66uYKtx1iEd7xwY9PpHiZjHcBKs9kWZ2DmfjpI4IxglN9JDi36AHtDSJ6u3LM0CCaX3J_QMMyHefJkNkYLA0AKafawaTPXncdHTkc4k0sbN18pc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 5,
                'monthlyPrice' => '87,45',
                'description' => 'Unprecedented performance for demanding workflows with M3 Max chip, Liquid Retina XDR display, and exceptional battery life.',
                'specs' => [
                    'Display' => '16.2" Liquid Retina XDR',
                    'Processor' => 'Apple M3 Max (14-core CPU)',
                    'RAM' => '36GB Unified Memory',
                    'Storage' => '1TB SSD',
                    'Graphics' => '30-core GPU',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'TOP 3',
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 16,
                'title' => 'Dell XPS 15 (9530)',
                'brand' => 'Dell',
                'price' => 1899.00,
                'oldPrice' => 2199.00,
                'image' => '',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 8,
                'monthlyPrice' => '47,45',
                'description' => 'Premium balance of power and portability with InfinityEdge display and NVIDIA RTX graphics for creators.',
                'specs' => [
                    'Display' => '15.6" FHD+ InfinityEdge',
                    'Processor' => 'Intel Core i7-13700H',
                    'RAM' => '16GB DDR5',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'NVIDIA RTX 4050',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 17,
                'title' => '    ',
                'brand' => 'Lenovo',
                'price' => 1599.00,
                'oldPrice' => 1899.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRuO5svXOgXe2i2GQpOC5IHdhwcEoMcbYKa_kzwTv9I89dDHVf55-8m6YVWFgrMexcKDzYe-GSq56l3GESB-toBXrKpzHAaYez5Iboowq7Nl2GIefse53h59UwO',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 12,
                'monthlyPrice' => '39,95',
                'description' => 'Ultra-light and durable business laptop with a superb keyboard and robust security for mobile professionals.',
                'specs' => [
                    'Display' => '14" WUXGA IPS',
                    'Processor' => 'Intel Core i7-1355U',
                    'RAM' => '16GB LPDDR5',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'Intel Iris Xe',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 18,
                'title' => 'ASUS ZenBook 14 OLED',
                'brand' => 'ASUS',
                'price' => 999.00,
                'oldPrice' => 1199.00,
                'image' => 'https://dlcdnwebimgs.asus.com/gain/46401036-702a-431e-927b-03613612293f/w800',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 10,
                'monthlyPrice' => '24,95',
                'description' => 'Elegant design with a stunning 2.8K OLED display and Intel Core Ultra processors for on-the-go productivity.',
                'specs' => [
                    'Display' => '14" 2.8K OLED, 120Hz',
                    'Processor' => 'Intel Core Ultra 5',
                    'RAM' => '16GB LPDDR5X',
                    'Storage' => '1TB SSD',
                    'Graphics' => 'Intel Arc Graphics',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 16
            ],
            [
                'id' => 19,
                'title' => 'HP Spectre x360 14',
                'brand' => 'HP',
                'price' => 1499.00,
                'oldPrice' => 1699.00,
                'image' => 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knivel/c08381629.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 9,
                'monthlyPrice' => '37,45',
                'description' => 'Versatile 2-in-1 convertible with a premium design and brilliant OLED touchscreen for creative professionals.',
                'specs' => [
                    'Display' => '14" 2.8K OLED Touch',
                    'Processor' => 'Intel Core Ultra 7',
                    'RAM' => '16GB LPDDR5X',
                    'Storage' => '1TB SSD',
                    'Graphics' => 'Intel Arc Graphics',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 20,
                'title' => 'MacBook Air 13" M2',
                'brand' => 'Apple',
                'price' => 999.00,
                'oldPrice' => 1099.00,
                'image' => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/macbook-air-midnight-select-20220606?wid=904&hei=840&fmt=jpeg&qlt=90&.v=1653084303790',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 15,
                'monthlyPrice' => '24,95',
                'description' => 'Super-portable with exceptional performance, Liquid Retina display, and all-day battery life in a thin design.',
                'specs' => [
                    'Display' => '13.6" Liquid Retina',
                    'Processor' => 'Apple M2 chip',
                    'RAM' => '8GB Unified Memory',
                    'Storage' => '256GB SSD',
                    'Graphics' => '8-core GPU',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 21,
                'title' => 'Acer Swift 3 OLED',
                'brand' => 'Acer',
                'price' => 749.00,
                'oldPrice' => 899.00,
                'image' => 'https://static.acer.com/up/resource/acer/laptops/swift-3-oled/gallery/20220622/Acer-Swift-3-OLED-SF314-512-gallery-01.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 20,
                'monthlyPrice' => '18,70',
                'description' => 'Brilliant 14" 2.8K OLED display and powerful Intel Core processors in a sleek, lightweight chassis.',
                'specs' => [
                    'Display' => '14" 2.8K OLED',
                    'Processor' => 'Intel Core i5-12500H',
                    'RAM' => '16GB LPDDR4X',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'Intel Iris Xe',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 16
            ],

            // DESKTOPY A PC
            [
                'id' => 22,
                'title' => 'ASUS ROG Strix G16 (2024)',
                'brand' => 'ASUS',
                'price' => 1599.00,
                'oldPrice' => 1799.00,
                'image' => 'https://dlcdnwebimgs.asus.com/gain/34007116-241b-4171-872a-43673010777e/w800',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 4,
                'monthlyPrice' => '39,95',
                'description' => 'Powerful gaming laptop with latest Intel Core processors and NVIDIA RTX graphics for competitive gaming.',
                'specs' => [
                    'Display' => '16" FHD+ 165Hz',
                    'Processor' => 'Intel Core i7-14700HX',
                    'RAM' => '16GB DDR5',
                    'Storage' => '1TB PCIe 4.0 SSD',
                    'Graphics' => 'NVIDIA RTX 4060',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'TOP 4',
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 23,
                'title' => 'HP OMEN 45L Gaming GT22',
                'brand' => 'HP',
                'price' => 2499.00,
                'oldPrice' => 2799.00,
                'image' => 'https://ssl-product-images.www8-hp.com/digmedialib/prodimg/knivel/c08471381.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 6,
                'monthlyPrice' => '62,45',
                'description' => 'High-performance desktop with unique Cryo Chamber cooling and top-tier NVIDIA GeForce RTX graphics.',
                'specs' => [
                    'Processor' => 'Intel Core i9-13900K',
                    'RAM' => '32GB DDR5',
                    'Storage' => '2TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4080',
                    'Cooling' => 'OMEN Cryo Chamber',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 10
            ],
            [
                'id' => 24,
                'title' => 'Lenovo Legion Tower 7i Gen 8',
                'brand' => 'Lenovo',
                'price' => 2199.00,
                'oldPrice' => 2499.00,
                'image' => 'https://psref.lenovo.com/syspool/Sys/Image/Legion/Legion_Tower_7i_Gen_8/Legion_Tower_7i_Gen_8_i1.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 5,
                'monthlyPrice' => '54,95',
                'description' => 'Formidable gaming desktop with advanced liquid cooling and extreme performance for unparalleled gaming.',
                'specs' => [
                    'Processor' => 'Intel Core i7-13700KF',
                    'RAM' => '32GB DDR5',
                    'Storage' => '1TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4070 Ti',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 25,
                'title' => 'MSI Aegis ZS',
                'brand' => 'MSI',
                'price' => 1199.00,
                'oldPrice' => 1399.00,
                'image' => 'https://asset.msi.com/resize/test/global/picture/image/feature/desktop/Aegis-ZS/Aegis-ZS-01.png?w=1200&h=630',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 8,
                'monthlyPrice' => '29,95',
                'description' => 'Stylish and powerful gaming desktop with AMD Ryzen and customizable RGB lighting for gamers and creators.',
                'specs' => [
                    'Processor' => 'AMD Ryzen 7 7700',
                    'RAM' => '16GB DDR5',
                    'Storage' => '1TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4060 Ti',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 26,
                'title' => 'Dell G15 Gaming Desktop',
                'brand' => 'Dell',
                'price' => 999.00,
                'oldPrice' => 1149.00,
                'image' => 'https://i.dell.com/is/image/Dell/g15-5530-laptop-gallery-1?wid=2000&hei=1500&fmt=png-alpha&qlt=100,1&resMode=sharp2&op_usm=1.75,0.3,2,0&fit=constrain,0&align=0,0',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 10,
                'monthlyPrice' => '24,95',
                'description' => 'Solid gaming performance in a compact and affordable package with reliable Intel and NVIDIA components.',
                'specs' => [
                    'Processor' => 'Intel Core i5-13400F',
                    'RAM' => '16GB DDR4',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'NVIDIA RTX 4060',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 27,
                'title' => 'Acer Predator Orion 3000',
                'brand' => 'Acer',
                'price' => 1099.00,
                'oldPrice' => 1299.00,
                'image' => 'https://static.acer.com/up/resource/acer/desktops/predator-orion-3000/gallery/20220622/Acer-Predator-Orion-3000-PO3-640-gallery-01.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 12,
                'monthlyPrice' => '27,45',
                'description' => 'Mid-tower gaming desktop delivering powerful performance for gaming and content creation with Orion cooling.',
                'specs' => [
                    'Processor' => 'Intel Core i7-13700F',
                    'RAM' => '16GB DDR4',
                    'Storage' => '1TB SSD',
                    'Graphics' => 'NVIDIA RTX 4060',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 28,
                'title' => 'Alza GameBox RTX4090',
                'brand' => 'Alza',
                'price' => 3499.00,
                'oldPrice' => 3999.00,
                'image' => 'https://asset.msi.com/resize/test/global/picture/image/feature/desktop/MEG-Aegis-Ti5/MEG-Aegis-Ti5-01.png?w=1200&h=630',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 3,
                'monthlyPrice' => '87,45',
                'description' => 'Extreme gaming PC built for uncompromising performance with RTX 4090 and advanced liquid cooling.',
                'specs' => [
                    'Processor' => 'AMD Ryzen 9 7950X3D',
                    'RAM' => '64GB DDR5',
                    'Storage' => '4TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4090',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'EXTRÉM',
                'discount_type' => 'percent',
                'discount_value' => 12
            ],

            // POWERBANKY
            [
                'id' => 30,
                'title' => 'Xiaomi 50W Power Bank 20000mAh',
                'brand' => 'Xiaomi',
                'price' => 45.00,
                'oldPrice' => 55.00,
                'image' => 'https://i01.appmifile.com/v1/MI_18455B3E414F93ED23C3D40809546C4C/pms_1637746129.6997412.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 50,
                'monthlyPrice' => null,
                'description' => 'High-speed charging for multiple devices including laptops with 50W fast charging and versatile USB-C.',
                'specs' => [
                    'Capacity' => '20000mAh',
                    'Output' => '50W Max',
                    'Ports' => 'USB-C, USB-A',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 18
            ],
            [
                'id' => 31,
                'title' => 'Samsung Wireless Battery Pack',
                'brand' => 'Samsung',
                'price' => 39.00,
                'oldPrice' => 49.00,
                'image' => 'https://images.samsung.com/is/image/samsung/p6pim/levant/2008/gallery/levant-wireless-battery-pack-eb-u3300-eb-u3300csegww-229009696?$650_519_PNG$',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 40,
                'monthlyPrice' => null,
                'description' => 'Convenient wireless charging for compatible devices and fast wired charging on the go.',
                'specs' => [
                    'Capacity' => '10000mAh',
                    'Wireless' => '25W Support',
                    'Ports' => 'USB-C',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 20
            ],
            [
                'id' => 32,
                'title' => 'Baseus Adaman 65W 20000mAh',
                'brand' => 'Baseus',
                'price' => 55.00,
                'oldPrice' => 69.00,
                'image' => 'https://cdn.shopify.com/s/files/1/0023/4198/0609/products/Baseus-Adaman-Metal-Digital-Display-Fast-Charge-Power-Bank-20000mAh-65W-Black-1.jpg?v=1628000000',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 30,
                'monthlyPrice' => null,
                'description' => 'Premium metal body with 65W Power Delivery for fast charging laptops and digital status display.',
                'specs' => [
                    'Capacity' => '20000mAh',
                    'Output' => '65W PD Max',
                    'Body' => 'Metal Casing',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 20
            ],
            [
                'id' => 33,
                'title' => 'Anker Nano Power Bank',
                'brand' => 'Anker',
                'price' => 35.00,
                'oldPrice' => 45.00,
                'image' => 'https://m.media-amazon.com/images/I/61+y3-1b+QL._AC_SL1500_.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 60,
                'monthlyPrice' => null,
                'description' => 'Compact and portable power solution with integrated USB-C connector for direct smartphone charging.',
                'specs' => [
                    'Capacity' => '5000mAh',
                    'Output' => '22.5W Max',
                    'Connector' => 'Integrated USB-C',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 22
            ],
            [
                'id' => 34,
                'title' => 'RAVPower 26800mAh PD',
                'brand' => 'RAVPower',
                'price' => 59.00,
                'oldPrice' => 79.00,
                'image' => 'https://m.media-amazon.com/images/I/71X8w1Q4-7L._AC_SL1500_.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 25,
                'monthlyPrice' => null,
                'description' => 'Enormous capacity with 30W Power Delivery output to quickly power up laptops and tablets.',
                'specs' => [
                    'Capacity' => '26800mAh',
                    'Output' => '30W PD Max',
                    'Ports' => 'USB-C, 2x USB-A',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 25
            ],
            [
                'id' => 35,
                'title' => 'Belkin BoostCharge 10K',
                'brand' => 'Belkin',
                'price' => 25.00,
                'oldPrice' => 35.00,
                'image' => 'https://www.belkin.com/dw/image/v2/BGMS_PRD/on/demandware.static/-/Sites-masterCatalog/default/dw62daca61/F7U063btBLK_product_image_hero.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 45,
                'monthlyPrice' => null,
                'description' => 'Slim and portable 10,000mAh power bank with certified safety features and 15W USB-C output.',
                'specs' => [
                    'Capacity' => '10000mAh',
                    'Output' => '15W Max',
                    'Safety' => 'Certified Protection',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 28
            ],

            // SMARTFÓNY - SÉRIA 2
            [
                'id' => 36,
                'title' => 'iPhone 15 Pro Max',
                'brand' => 'Apple',
                'price' => 1199.00,
                'oldPrice' => 1299.00,
                'image' => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-max-finish-select-202309-6-7inch-naturaltitanium?wid=940&hei=1112&fmt=png-alpha&.v=1692845702708',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 8,
                'monthlyPrice' => '29,95',
                'description' => 'Larger 6.7" display with 5x optical zoom and A17 Pro chip in a durable titanium design.',
                'specs' => [
                    'Display' => '6.7" Super Retina XDR',
                    'Processor' => 'A17 Pro chip',
                    'RAM' => '8GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '48MP Main, 12MP 5x Zoom',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'TOP 5',
                'discount_type' => 'percent',
                'discount_value' => 7
            ],
            [
                'id' => 37,
                'title' => 'Samsung Galaxy Z Fold 5',
                'brand' => 'Samsung',
                'price' => 1599.00,
                'oldPrice' => 1799.00,
                'image' => 'https://images.samsung.com/is/image/samsung/p6pim/levant/2307/gallery/levant-galaxy-z-fold5-f946-sm-f946bzeamea-537660429?$650_519_PNG$',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 5,
                'monthlyPrice' => '39,95',
                'description' => 'Revolutionary foldable with a 7.6" main display for immersive viewing and advanced multitasking.',
                'specs' => [
                    'Display' => '7.6" Dynamic AMOLED 2X',
                    'Processor' => 'Snapdragon 8 Gen 2 for Galaxy',
                    'RAM' => '12GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '50MP Triple Camera',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 38,
                'title' => 'Google Pixel 8',
                'brand' => 'Google',
                'price' => 699.00,
                'oldPrice' => 799.00,
                'image' => 'https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Google_Pixel_8.width-10000.format-webp.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 15,
                'monthlyPrice' => '17,45',
                'description' => 'Smart and compact with a brilliant 6.2" Actua display and advanced Google AI camera features.',
                'specs' => [
                    'Display' => '6.2" Actua OLED',
                    'Processor' => 'Google Tensor G3',
                    'RAM' => '8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '50MP Main, 12MP Ultra-Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 39,
                'title' => 'OnePlus 11 5G',
                'brand' => 'OnePlus',
                'price' => 599.00,
                'oldPrice' => 699.00,
                'image' => 'https://image.oneplus.com/content/dam/oplus/common/product-images/11/11-green-1.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 12,
                'monthlyPrice' => '14,95',
                'description' => 'Flagship performance with Snapdragon 8 Gen 2, 120Hz AMOLED, and ultra-fast 100W charging.',
                'specs' => [
                    'Display' => '6.7" AMOLED, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 2',
                    'RAM' => '8GB, 16GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '50MP Main Hasselblad',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 40,
                'title' => 'Xiaomi 13T Pro',
                'brand' => 'Xiaomi',
                'price' => 549.00,
                'oldPrice' => 649.00,
                'image' => 'https://i01.appmifile.com/v1/MI_18455B3E414F93ED23C3D40809546C4C/pms_1695692288.99023667.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 18,
                'monthlyPrice' => '13,70',
                'description' => 'Brilliant 144Hz CrystalRes AMOLED and Leica professional camera with ultra-fast 120W HyperCharge.',
                'specs' => [
                    'Display' => '6.67" CrystalRes AMOLED, 144Hz',
                    'Processor' => 'Dimensity 9200+',
                    'RAM' => '12GB',
                    'Storage' => '512GB',
                    'Camera' => '50MP Main Leica',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 41,
                'title' => 'Motorola Edge 40 Pro',
                'brand' => 'Motorola',
                'price' => 599.00,
                'oldPrice' => 699.00,
                'image' => 'https://www.motorola.com/sites/default/files/moto-edge-40-pro-pdp-render-1-black.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 20,
                'monthlyPrice' => '14,95',
                'description' => 'Fluid 165Hz pOLED display and ultra-fast 125W TurboPower charging on a clean Android experience.',
                'specs' => [
                    'Display' => '6.67" pOLED, 165Hz',
                    'Processor' => 'Snapdragon 8 Gen 2',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Camera' => '50MP Triple Camera',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 42,
                'title' => 'Nothing Phone (2)',
                'brand' => 'Nothing',
                'price' => 529.00,
                'oldPrice' => 599.00,
                'image' => 'https://nothing.tech/cdn/shop/files/Phone_2_Black_Front_Back_3_4_Angle_Glyph_On_1000x.png?v=1688556702',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 14,
                'monthlyPrice' => '13,20',
                'description' => 'Unique Glyph Interface and transparent design with a stunning 6.7" LTPO OLED display.',
                'specs' => [
                    'Display' => '6.7" LTPO OLED, 120Hz',
                    'Processor' => 'Snapdragon 8+ Gen 1',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Interface' => 'Glyph Interface',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],

            // SLÚCHADLÁ
            [
                'id' => 43,
                'title' => 'Sony WH-1000XM5',
                'brand' => 'Sony',
                'price' => 299.00,
                'oldPrice' => 349.00,
                'image' => 'https://www.sony.com/image/be1a430932223703134937747970114f?fmt=png-alpha&wid=400',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 25,
                'monthlyPrice' => '7,45',
                'description' => 'Industry-leading noise cancellation and exceptional sound quality for a superior listening experience.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'ANC' => 'Industry-leading',
                    'Battery' => '30 hours with ANC',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => 'TOP 6',
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 44,
                'title' => 'Bose QuietComfort Ultra',
                'brand' => 'Bose',
                'price' => 399.00,
                'oldPrice' => 429.00,
                'image' => 'https://assets.bose.com/content/dam/Bose_DAM/Web/consumer_electronics/global/products/sluchadla/qc_ultra_sluchadla/product_page_images/qc_ultra_hp_black_01.png/jcr:content/renditions/cq5dam.web.1000.1000.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 18,
                'monthlyPrice' => '9,95',
                'description' => 'World-class noise cancellation and groundbreaking Immersive Audio for a captivating sound experience.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Audio' => 'Immersive Audio',
                    'ANC' => 'World-class',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 7
            ],
            [
                'id' => 45,
                'title' => 'Apple AirPods Max',
                'brand' => 'Apple',
                'price' => 499.00,
                'oldPrice' => 549.00,
                'image' => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/airpods-max-hero-select-202011?wid=940&hei=1112&fmt=png-alpha&.v=1604021227000',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 12,
                'monthlyPrice' => '12,45',
                'description' => 'High-fidelity audio combined with industry-leading Active Noise Cancellation and a luxurious design.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Chip' => 'Apple H1 (x2)',
                    'Audio' => 'Spatial Audio',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 46,
                'title' => 'Sennheiser Momentum 4 Wireless',
                'brand' => 'Sennheiser',
                'price' => 279.00,
                'oldPrice' => 329.00,
                'image' => 'https://assets.sennheiser.com/img/1000/MOMENTUM_4_Wireless_Black_01.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 20,
                'monthlyPrice' => '6,95',
                'description' => 'Exceptional sound quality and adaptive noise cancellation with an incredible 60-hour battery life.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Battery' => '60 hours',
                    'Audio' => 'Signature Sound',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 47,
                'title' => 'JBL Tune 770NC',
                'brand' => 'JBL',
                'price' => 99.00,
                'oldPrice' => 119.00,
                'image' => 'https://www.jbl.com/on/demandware.static/-/Sites-masterCatalog_Harman/default/dw76572731/JBL_Tune_770NC_Product_Image_Hero_Black.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 35,
                'monthlyPrice' => null,
                'description' => 'Powerful JBL Pure Bass Sound with active noise cancellation and up to 70 hours of battery life.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Audio' => 'Pure Bass Sound',
                    'Battery' => '70 hours',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 16
            ],
            [
                'id' => 48,
                'title' => 'Samsung Galaxy Buds2 Pro',
                'brand' => 'Samsung',
                'price' => 179.00,
                'oldPrice' => 229.00,
                'image' => 'https://images.samsung.com/is/image/samsung/p6pim/levant/2208/gallery/levant-galaxy-buds2-pro-sm-r510nzaamea-533066604?$650_519_PNG$',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 40,
                'monthlyPrice' => null,
                'description' => 'Immersive 24-bit Hi-Fi audio and intelligent Active Noise Cancellation in a comfortable design.',
                'specs' => [
                    'Type' => 'True Wireless',
                    'Audio' => '24-bit Hi-Fi',
                    'ANC' => 'Intelligent',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 21
            ],
            [
                'id' => 49,
                'title' => 'Nothing Ear (2)',
                'brand' => 'Nothing',
                'price' => 129.00,
                'oldPrice' => 149.00,
                'image' => 'https://nothing.tech/cdn/shop/files/Ear_2_White_Front_Back_1000x.png?v=1680182824',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 30,
                'monthlyPrice' => null,
                'description' => 'Transparent design with personalized ANC and Hi-Res Audio for a pure sound experience.',
                'specs' => [
                    'Type' => 'True Wireless',
                    'Audio' => 'Hi-Res, LHDC 5.0',
                    'Design' => 'Transparent',
                ],
                'service' => 'Do polnoci objednáš, ráno v AlzaBoxe máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
        ];

        foreach ($products as $productData) {
            // Convert specs array to formatted text
            if (is_array($productData['specs'])) {
                $specsText = [];
                foreach ($productData['specs'] as $key => $value) {
                    $specsText[] = "$key: $value";
                }
                $productData['specs'] = implode("\n", $specsText);
            }
            Product::create($productData);
        }
    }
}