<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            // SMARTFÓNY - SÉRIA 1
            [
                'id' => 1,
                'title' => 'iPhone 15 Pro',
                'brand' => 'Apple',
                'price' => 999.00,
                'oldPrice' => 1099.00,
                'image' => 'https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-15-pro-finish-select-202309-6-1inch-naturaltitanium?wid=940&hei=1112&fmt=png-alpha&.v=1692845702708',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 10,
                'monthlyPrice' => '24,95',
                'description' => 'iPhone 15 Pro je vykovaný z titánu a obsahuje revolučný čip A17 Pro, prispôsobiteľné tlačidlo Action a všestrannejší profesionálny kamerový systém.',
                'specs' => [
                    'Display' => '6.1" Super Retina XDR, ProMotion',
                    'Processor' => 'A17 Pro chip',
                    'RAM' => '8GB',
                    'Storage' => '128GB, 256GB, 512GB, 1TB',
                    'Camera' => '48MP Main, 12MP Ultra Wide, 12MP 3x Telephoto',
                ],
                'variants' => [
                    'storage' => ['128GB', '256GB', '512GB', '1TB']
                ],
                'variant_pricing' => [
                    'storage' => ['128GB' => 0, '256GB' => 100, '512GB' => 200, '1TB' => 400]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'TOP 1',
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 2,
                'title' => 'Samsung Galaxy S24 Ultra',
                'brand' => 'Samsung',
                'price' => 1299.99,
         //       'oldPrice' => 1399.99,
                'image' => 'https://img-cdn.heureka.group/v1/7ebb2d87-1861-4543-bc67-4db42c814142.jpg?width=2000&height=2000&fit=upsize',
                'rating' => 0,
                 'reviews' => 0,
                'category' => 'phones',
                'stock' => 8,
                'monthlyPrice' => '32,50',
                'description' => 'Konečný Galaxy smartfón s novou titánovou vonkajšou stranou, 6,8" plochým displejom a funkciami Galaxy AI pre zvýšenú kreativitu a produktivitu.',
                'specs' => [
                    'Display' => '6.8" Dynamic AMOLED 2X, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 3 for Galaxy',
                    'RAM' => '12GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '200MP Main, 50MP 5x Zoom, 12MP Ultra-Wide',
                ],
                'variants' => [
                    'storage' => ['256GB', '512GB', '1TB']
                ],
                'variant_pricing' => [
                    'storage' => ['256GB' => 0, '512GB' => 150, '1TB' => 400]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 7
            ],
            [
                'id' => 3,
                'title' => 'Google Pixel 8 Pro',
                'brand' => 'Google',
                'price' => 999.00,
                'oldPrice' => 1099.00,
                'image' => 'https://image.alza.cz/products/GPX1075b1/GPX1075b1.jpg?width=500&height=500',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 15,
                'monthlyPrice' => '24,95',
                'description' => 'Najsilnejší Pixel dosiaľ s AI od Googlu, profesionálnym trojitým kamerovým systémom a vlastným čipom Google Tensor G3.',
                'specs' => [
                    'Display' => '6.7" Super Actua LTPO OLED',
                    'Processor' => 'Google Tensor G3',
                    'RAM' => '12GB',
                    'Storage' => '128GB, 256GB, 512GB, 1TB',
                    'Camera' => '50MP Main, 48MP Ultra-Wide, 48MP 5x Telephoto',
                ],
                'variants' => [
                    'storage' => ['128GB', '256GB', '512GB', '1TB']
                ],
                'variant_pricing' => [
                    'storage' => ['128GB' => 0, '256GB' => 100, '512GB' => 200, '1TB' => 400]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 4,
                'title' => 'Xiaomi 14 Pro',
                'brand' => 'Xiaomi',
                'price' => 799.00,
                'oldPrice' => 899.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTNObkdlb8r0N36mYOiInisVRTEXCKgVGybIRgOojT6YOSk4GS1b8PLs9W1zavAkjHpeJZvHTryDEcGMjv5YenlATrrAsBO-dgOr7AVekQ0268St53y0NBd4w&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 20,
                'monthlyPrice' => '19,95',
                'description' => 'S legendárnym optickým objektívom Leica Summilux, procesorom Snapdragon 8 Gen 3 a úplne novým HyperOS.',
                'specs' => [
                    'Display' => '6.73" LTPO AMOLED, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'RAM' => '12GB, 16GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '50MP Main, 50MP Telephoto, 50MP Ultra-Wide',
                ],
                'variants' => [
                    'ram' => ['12GB', '16GB'],
                    'storage' => ['256GB', '512GB', '1TB']
                ],
                'variant_pricing' => [
                    'ram' => ['12GB' => 0, '16GB' => 50],
                    'storage' => ['256GB' => 0, '512GB' => 150, '1TB' => 400]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 5,
                'title' => 'OnePlus 12',
                'brand' => 'OnePlus',
                'price' => 799.00,
                'oldPrice' => 899.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQ3VS7KY6yFPun5RvJ0NTzdcrQclJjt7uGGqy-I0DkfLshm4lLu4cSR6DBoZaUDj03DRjmKE1S1ACVmHikgBhCbkcrOyQzkdLfsJdnp4i4umP3uB21DOBeNWrGpeWvU&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 12,
                'monthlyPrice' => '19,95',
                'description' => 'Rýchlosť a hladkosť predefinovaná procesorom Snapdragon 8 Gen 3, nádherným displejom 120Hz ProXDR a systémom kamery Hasselblad.',
                'specs' => [
                    'Display' => '6.82" LTPO AMOLED, 120Hz ProXDR',
                    'Processor' => 'Snapdragon 8 Gen 3',
                    'RAM' => '12GB, 16GB, 24GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '50MP Main, 48MP Ultra-Wide, 64MP Periscope',
                ],
                'variants' => [
                    'ram' => ['12GB', '16GB', '24GB'],
                    'storage' => ['256GB', '512GB', '1TB']
                ],
                'variant_pricing' => [
                    'ram' => ['12GB' => 0, '16GB' => 50, '24GB' => 120],
                    'storage' => ['256GB' => 0, '512GB' => 150, '1TB' => 400]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 6,
                'title' => 'iPhone 14',
                'brand' => 'Apple',
                'price' => 699.00,
                'oldPrice' => 799.00,
                'image' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQr4OteYxq-5uyqvadd1Vb-WOyVokE6mxVPp72FZ37Pe9Ls62Gc_Z5s7bfdf6CX8SIxkWsXZfjYaTA2ZfCt4NPWoA5Ib25riXl4VkLmiJwHMf_-_7ak--L6fWzpwy7tH7qvnwyrYB0&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 25,
                'monthlyPrice' => '17,45',
                'description' => 'Odolný dizajn, pôsobivý duálny kamerový systém a priekopnícke bezpečnostné funkcie ako napríklad detekcia zrážky.',
                'specs' => [
                    'Display' => '6.1" Super Retina XDR',
                    'Processor' => 'A15 Bionic chip',
                    'RAM' => '6GB',
                    'Storage' => '128GB, 256GB, 512GB',
                    'Camera' => '12MP Main, 12MP Ultra Wide',
                ],
                'variants' => [
                    'storage' => ['128GB', '256GB', '512GB']
                ],
                'variant_pricing' => [
                    'storage' => ['128GB' => 0, '256GB' => 80, '512GB' => 180]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 7,
                'title' => 'Samsung Galaxy A54',
                'brand' => 'Samsung',
                'price' => 349.00,
                'oldPrice' => 449.00,
                'image' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSqDjI-5w-O82l_AnsM3TIRFaJ6CZZyIjdJ_RK4g1oEUvrw2pCD1fyc-LUz5kI9wH7mJtBKzX8WPfnsjTUGdrwrQ4q7WYrq',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 30,
                'monthlyPrice' => '8,70',
                'description' => 'Farebný displej Super AMOLED, všestranný trojitý kamerový systém a dlhodobá batéria na denné použitie.',
                'specs' => [
                    'Display' => '6.4" Super AMOLED, 120Hz',
                    'Processor' => 'Exynos 1380',
                    'RAM' => '6GB, 8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '50MP Main, 12MP Ultra Wide, 5MP Macro',
                ],
                'variants' => [
                    'ram' => ['6GB', '8GB'],
                    'storage' => ['128GB', '256GB']
                ],
                'variant_pricing' => [
                    'ram' => ['6GB' => 0, '8GB' => 30],
                    'storage' => ['128GB' => 0, '256GB' => 50]
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 22
            ],

            // TABLETY
            [
                'id' => 8,
                'title' => 'iPad Pro 13" M4',
                'brand' => 'Apple',
                'price' => 1299.00,
                'oldPrice' => 1499.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSH7pIFGVBGoyfv1yiFxiTBpkuXoQX35W0Xok0cgthlaQoDtukttyrwtyYPxSiaUXsaOm6GgYyM1zh4Rs3WVY2QC7_AjK7QKCWFP2ekkMOXP8N_EyfLzYk-3jgaTIHCWOyMZqZZwIWGkHQ&usqp=CAc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 8,
                'monthlyPrice' => '32,45',
                'description' => 'Neuveriteľne tenký a ľahký, s revolučným displejom Ultra Retina XDR Tandem OLED a oslepujúco rýchlym výkonom M4.',
                'specs' => [
                    'Display' => '13" Ultra Retina XDR (Tandem OLED)',
                    'Processor' => 'Apple M4 chip',
                    'RAM' => '8GB, 16GB',
                    'Storage' => '256GB, 512GB, 1TB, 2TB',
                    'Camera' => '12MP Wide, LiDAR Scanner',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'TOP 2',
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 9,
                'title' => 'Samsung Galaxy Tab S9 Ultra',
                'brand' => 'Samsung',
                'price' => 1099.00,
                'oldPrice' => 1299.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRcRfUJTk6pFfyfmIegdKhZ6AuuNy5w832SLcDMzYdh35glAB5V70_NEXfYjPG289jgbAVg4JPBnag0Dc-g1isDdWg7mjLy',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 10,
                'monthlyPrice' => '27,45',
                'description' => 'Obrovský 14,6" displej Dynamic AMOLED 2X, Snapdragon 8 Gen 2 pre Galaxy a zahrnutý S Pen na prácu a zábavu.',
                'specs' => [
                    'Display' => '14.6" Dynamic AMOLED 2X, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 2 for Galaxy',
                    'RAM' => '12GB, 16GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '13MP Main, 8MP Ultra-Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 10,
                'title' => 'iPad Air 11" M2',
                'brand' => 'Apple',
                'price' => 599.00,
                'oldPrice' => 699.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQl7G0z6kxc50hSQ7tU9qHZvU-_4Yf4rckivNUNbY8wpIr9ss2ztozY6oTQgICtNul1LELv1L_Dj-lS8R7P3F6smrx-21qRfr6-VGfOsVpu8_tcBBij05cMDjSU',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 15,
                'monthlyPrice' => '14,95',
                'description' => 'Neuveriteľný výkon a pokročilé funkcie v tenkom a ľahkom dizajne s výkonným čipom M2.',
                'specs' => [
                    'Display' => '11" Liquid Retina',
                    'Processor' => 'Apple M2 chip',
                    'RAM' => '8GB',
                    'Storage' => '128GB, 256GB, 512GB, 1TB',
                    'Camera' => '12MP Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 11,
                'title' => 'Samsung Galaxy Tab S9',
                'brand' => 'Samsung',
                'price' => 799.00,
                'oldPrice' => 899.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSTgAYfogFLNL_t_wvG-J4PWli37-CyFNqD7RoZvAnt6Y6NgpYRSAHn3LEZIzX_yULXJcIrZ-iHl38agPFGzLOwrPnN-tXdGMA4jVRCdoxjSOsKv8_On2z-fFs4',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 12,
                'monthlyPrice' => '19,95',
                'description' => 'Ohromujúci 11" displej Dynamic AMOLED 2X, výkonný výkon a odolnosť IP68 voči vode a prachu.',
                'specs' => [
                    'Display' => '11" Dynamic AMOLED 2X, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 2 for Galaxy',
                    'RAM' => '8GB, 12GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '13MP Main',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 12,
                'title' => 'Lenovo Tab P12',
                'brand' => 'Lenovo',
                'price' => 329.00,
                'oldPrice' => 379.00,
                'image' => 'https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQb3aXDVc0ZxIEcpFRytbNIJKzWd2_11aJAsehausYiuYI-Pv_np3FOZz6O5cJeiSXuj-OwUtcrPSLD_q13VCn_bUrE95hn7R_FtSRndPwbBLwASmeC9xoVOw',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 18,
                'monthlyPrice' => '8,20',
                'description' => 'Univerzálny tablet na zábavu a produktivitu s veľkým 12,7" displejom 3K a štyrmi reproduktormi JBL.',
                'specs' => [
                    'Display' => '12.7" 3K LCD',
                    'Processor' => 'MediaTek Dimensity 7050',
                    'RAM' => '4GB, 8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '8MP Rear, 13MP Front',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 13,
                'title' => 'iPad 10.9" (2022)',
                'brand' => 'Apple',
                'price' => 399.00,
                'oldPrice' => 449.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQXipsRyYabvbp6B_EGjc7AwpKnU3-_PBhyxa0EWxX_1WddiKJPS6b7VwlnC_gXXxYvircqDSULldU1lpRiNVdmsawRgNwkanPm7jv_2Iz3Rvpte_G0LBvFGg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 20,
                'monthlyPrice' => '9,95',
                'description' => 'Dizajn bez rámov s 10,9" displejom Liquid Retina, poháňaný čipom A14 Bionic pre každodenné úlohy.',
                'specs' => [
                    'Display' => '10.9" Liquid Retina',
                    'Processor' => 'A14 Bionic chip',
                    'RAM' => '4GB',
                    'Storage' => '64GB, 256GB',
                    'Camera' => '12MP Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 14,
                'title' => 'Xiaomi Pad 6',
                'brand' => 'Xiaomi',
                'price' => 299.00,
                'oldPrice' => 349.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTYu3MMxNFNOqWltvLfg48CE0EVh9woUevBbB1bAziQsjWWzA_K56pdi52oiWb-z1GKgGZX7xs79o9IaqDF5OQ-3gB4RExsp6-1Ej_coxv7jBFiAoy0V6Iazg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'tablets',
                'stock' => 25,
                'monthlyPrice' => '7,45',
                'description' => 'Pohlcujúci 11" displej 2,8K 144Hz a výkonný procesor Snapdragon 870 v elegantnom kovom dizajne.',
                'specs' => [
                    'Display' => '11" 2.8K LCD, 144Hz',
                    'Processor' => 'Snapdragon 870',
                    'RAM' => '6GB, 8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '13MP Rear, 8MP Front',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],

            // NOTEBOOKY
            [
                'id' => 15,
                'title' => 'MacBook Pro 16" M3 Max',
                'brand' => 'Apple',
                'price' => 3499.00,
                'oldPrice' => 3999.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTI7esxi_DL66uYKtx1iEd7xwY9PpHiZjHcBKs9kWZ2DmfjpI4IxglN9JDi36AHtDSJ6u3LM0CCaX3J_QMMyHefJkNkYLA0AKafawaTPXncdHTkc4k0sbN18pc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 5,
                'monthlyPrice' => '87,45',
                'description' => 'Bezprecedentný výkon pre náročné pracovné postupy s čipom M3 Max, displejom Liquid Retina XDR a výnimočnou výdržou batérie.',
                'specs' => [
                    'Display' => '16.2" Liquid Retina XDR',
                    'Processor' => 'Apple M3 Max (14-core CPU)',
                    'RAM' => '36GB Unified Memory',
                    'Storage' => '1TB SSD',
                    'Graphics' => '30-core GPU',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'TOP 3',
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 16,
                'title' => 'Dell XPS 15 (9530)',
                'brand' => 'Dell',
                'price' => 1899.00,
                'oldPrice' => 2199.00,
                'image' => 'https://doc.smarty.sk/pic/FDY7G00101-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 8,
                'monthlyPrice' => '47,45',
                'description' => 'Prémium rovnováha sily a prenosnosti s displejom InfinityEdge a grafikou NVIDIA RTX pre tvorcov.',
                'specs' => [
                    'Display' => '15.6" FHD+ InfinityEdge',
                    'Processor' => 'Intel Core i7-13700H',
                    'RAM' => '16GB DDR5',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'NVIDIA RTX 4050',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 17,
                'title' => '    ',
                'brand' => 'Lenovo',
                'price' => 1599.00,
                'oldPrice' => 1899.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRuO5svXOgXe2i2GQpOC5IHdhwcEoMcbYKa_kzwTv9I89dDHVf55-8m6YVWFgrMexcKDzYe-GSq56l3GESB-toBXrKpzHAaYez5Iboowq7Nl2GIefse53h59UwO',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 12,
                'monthlyPrice' => '39,95',
                'description' => 'Ultra ľahký a odolný obchodný notebook so skvelou klávesnicou a robustným bezpečnostným systémom pre mobilných profesionálov.',
                'specs' => [
                    'Display' => '14" WUXGA IPS',
                    'Processor' => 'Intel Core i7-1355U',
                    'RAM' => '16GB LPDDR5',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'Intel Iris Xe',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 18,
                'title' => 'ASUS ZenBook 14 OLED',
                'brand' => 'ASUS',
                'price' => 999.00,
                'oldPrice' => 1199.00,
                'image' => 'https://doc.smarty.sk/pic/d_7c2a45ce044c49b389259989aa5bc897-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 10,
                'monthlyPrice' => '24,95',
                'description' => 'Elegantný dizajn s ohromujúcim displejom 2,8K OLED a procesormi Intel Core Ultra pre produktivitu na cestách.',
                'specs' => [
                    'Display' => '14" 2.8K OLED, 120Hz',
                    'Processor' => 'Intel Core Ultra 5',
                    'RAM' => '16GB LPDDR5X',
                    'Storage' => '1TB SSD',
                    'Graphics' => 'Intel Arc Graphics',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 16
            ],
            [
                'id' => 19,
                'title' => 'HP Spectre x360 14',
                'brand' => 'HP',
                'price' => 1499.00,
                'oldPrice' => 1699.00,
                'image' => 'https://doc.smarty.sk/pic/d_7c2a45ce044c49b389259989aa5bc897-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 9,
                'monthlyPrice' => '37,45',
                'description' => 'Univerzálny 2-v-1 konvertibilný notebook s prémiovým dizajnom a skvelou OLED dotykom obrazovkou pre kreatívnych profesionálov.',
                'specs' => [
                    'Display' => '14" 2.8K OLED Touch',
                    'Processor' => 'Intel Core Ultra 7',
                    'RAM' => '16GB LPDDR5X',
                    'Storage' => '1TB SSD',
                    'Graphics' => 'Intel Arc Graphics',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 20,
                'title' => 'MacBook Air 13,6" M2',
                'brand' => 'Apple',
                'price' => 999.00,
                'oldPrice' => 1099.00,
                'image' => 'https://doc.smarty.sk/pic/d_7c2a45ce044c49b389259989aa5bc897-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 15,
                'monthlyPrice' => '24,95',
                'description' => 'Super-prenosný s výnimočným výkonom, displejom Liquid Retina a celodennou výdržou batérie v tenkom dizajne.',
                'specs' => [
                    'Display' => '13.6" Liquid Retina',
                    'Processor' => 'Apple M2 chip',
                    'RAM' => '8GB Unified Memory',
                    'Storage' => '256GB SSD',
                    'Graphics' => '8-core GPU',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 21,
                'title' => 'Acer Swift 3 OLED',
                'brand' => 'Acer',
                'price' => 749.00,
                'oldPrice' => 899.00,
                'image' => 'https://doc.smarty.sk/pic/K0C7000P01-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'notebooks',
                'stock' => 20,
                'monthlyPrice' => '18,70',
                'description' => 'Skvelý 14" displej 2,8K OLED a výkonné procesory Intel Core v elegantnom ľahkom podvozku.',
                'specs' => [
                    'Display' => '14" 2.8K OLED',
                    'Processor' => 'Intel Core i5-12500H',
                    'RAM' => '16GB LPDDR4X',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'Intel Iris Xe',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 16
            ],

            // DESKTOPY A PC
            [
                'id' => 22,
                'title' => 'ASUS ROG Strix G16 (2024)',
                'brand' => 'ASUS',
                'price' => 1599.00,
                'oldPrice' => 1799.00,
                'image' => 'https://doc.smarty.sk/pic/F4MD000J01-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 4,
                'monthlyPrice' => '39,95',
                'description' => 'Výkonný hernický notebook s najnovšími procesormi Intel Core a grafikou NVIDIA RTX na konkurenčné hranie.',
                'specs' => [
                    'Display' => '16" FHD+ 165Hz',
                    'Processor' => 'Intel Core i7-14700HX',
                    'RAM' => '16GB DDR5',
                    'Storage' => '1TB PCIe 4.0 SSD',
                    'Graphics' => 'NVIDIA RTX 4060',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'TOP 4',
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 23,
                'title' => 'HP OMEN 45L Gaming GT22',
                'brand' => 'HP',
                'price' => 2499.00,
                'oldPrice' => 2799.00,
                'image' => 'https://cdn.aukro.cz/images/sk1771714621007/hp-omen-45l-gt22-i9-13900k-32gb-2tb-rtx-4080-super-16gb-260608557.jpeg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 6,
                'monthlyPrice' => '62,45',
                'description' => 'Vysoko výkonný stolný počítač s jedinečným chladením Cryo Chamber a špičkou grafikou NVIDIA GeForce RTX.',
                'specs' => [
                    'Processor' => 'Intel Core i9-13900K',
                    'RAM' => '32GB DDR5',
                    'Storage' => '2TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4080',
                    'Cooling' => 'OMEN Cryo Chamber',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 10
            ],
            [
                'id' => 24,
                'title' => 'Lenovo Legion Tower 7i Gen 8',
                'brand' => 'Lenovo',
                'price' => 2199.00,
                'oldPrice' => 2499.00,
                'image' => 'https://cdn.aukro.cz/images/sk1771714621918/lenovo-legion-t7-34irz8-i9-13900kf-32gb-2tb-rx-9070-xt-16gb-260608562.jpeg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 5,
                'monthlyPrice' => '54,95',
                'description' => 'Formidabilný hernícky počítač s pokročilým kvapalinovým chladením a extrémnym výkonom pre bezkonkurenčnú hru.',
                'specs' => [
                    'Processor' => 'Intel Core i7-13700KF',
                    'RAM' => '32GB DDR5',
                    'Storage' => '1TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4070 Ti',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 25,
                'title' => 'MSI Aegis ZS',
                'brand' => 'MSI',
                'price' => 1199.00,
                'oldPrice' => 1399.00,
                'image' => 'https://image.alza.cz/products/TB256i14/TB256i14.jpg?width=1400&height=1400',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 8,
                'monthlyPrice' => '29,95',
                'description' => 'Štýlový a výkonný hernícky počítač s AMD Ryzen a prispôsobiteľným RGB osvetlením pre hráčov a tvorcov.',
                'specs' => [
                    'Processor' => 'AMD Ryzen 7 7700',
                    'RAM' => '16GB DDR5',
                    'Storage' => '1TB NVMe SSD',
                    'Graphics' => 'NVIDIA RTX 4060 Ti',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 26,
                'title' => 'DELL Tower Plus EBT2250',
                'brand' => 'Dell',
                'price' => 999.00,
                'oldPrice' => 1149.00,
                'image' => 'https://dt-shop.sk/media/product_image/PCD187800_275991.jpg.688x0_q85ss0_crop_replace_alpha-%23fff.jpg.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 10,
                'monthlyPrice' => '24,95',
                'description' => 'Solidný hernícky výkon v kompaktnom a cenovo dostupnom balíčku so spoľahlivými komponentmi Intel a NVIDIA.',
                'specs' => [
                    'Processor' => 'Intel Core i5-13400F',
                    'RAM' => '16GB DDR4',
                    'Storage' => '512GB SSD',
                    'Graphics' => 'NVIDIA RTX 4060',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
            [
                'id' => 27,
                'title' => 'Acer Predator Orion 3000',
                'brand' => 'Acer',
                'price' => 1099.00,
                'oldPrice' => 1299.00,
                'image' => 'https://cdn.aukro.cz/images/sk1770832664549/acer-predator-orion-3000-i7-11700f-1tb-ssd-1tb-hdd-32g-rtx3070-w10-258855304.jpeg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 12,
                'monthlyPrice' => '27,45',
                'description' => 'Hernícky stolný počítač so stredným vežom s výkonným výkonom pre hernú a tvorbu obsahu s chladením Orion.',
                'specs' => [
                    'Processor' => 'Intel Core i7-13700F',
                    'RAM' => '16GB DDR4',
                    'Storage' => '1TB SSD',
                    'Graphics' => 'NVIDIA RTX 4060',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 28,
                'title' => 'Alza GameBox RTX4090',
                'brand' => 'Alza',
                'price' => 3499.00,
                'oldPrice' => 3999.00,
                'image' => 'https://image.alza.cz/products/AZgbur7r4090a1/AZgbur7r4090a1.jpg?width=500&height=500',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'pcs',
                'stock' => 3,
                'monthlyPrice' => '87,45',
                'description' => 'Extrémny hernícky počítač vybudovaný na bez kompromisný výkon s RTX 4090 a pokročilým kvapalinovým chladením.',
                'specs' => [
                    'Processor' => 'AMD Ryzen 9 7950X3D',
                    'RAM' => '64GB DDR5',
                    'Storage' => '2TB SSD',
                    'Graphics' => 'NVIDIA RTX 4090',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'EXTRÉM',
                'discount_type' => 'percent',
                'discount_value' => 12
            ],

            // POWERBANKY
            [
                'id' => 30,
                'title' => 'Xiaomi 50W Power Bank 20000mAh',
                'brand' => 'Xiaomi',
                'price' => 45.00,
                'oldPrice' => 55.00,
                'image' => 'https://image.nay.sk/foto/500/0/3/0/product_4889030.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 50,
                'monthlyPrice' => null,
                'description' => 'Vysokorýchlostné nabíjanie viacerých zariadení vrátane laptopov s 50W rýchlosťou nabíjania a všestranným USB-C.',
                'specs' => [
                    'Capacity' => '20000mAh',
                    'Output' => '50W Max',
                    'Ports' => 'USB-C, USB-A',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 18
            ],
            [
                'id' => 31,
                'title' => 'Samsung Wireless Battery Pack',
                'brand' => 'Samsung',
                'price' => 39.00,
                'oldPrice' => 49.00,
                'image' => 'https://image.alza.cz/products/SAAB0118a16/SAAB0118a16.jpg?width=500&height=500',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 40,
                'monthlyPrice' => null,
                'description' => 'Pohodlné bezdrôtové nabíjanie pre kompatibilné zariadenia a rýchle drôtové nabíjanie na cestách.',
                'specs' => [
                    'Capacity' => '10000mAh',
                    'Wireless' => '25W Support',
                    'Ports' => 'USB-C',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 20
            ],
            [
                'id' => 32,
                'title' => 'Baseus Adaman 65W 20000mAh',
                'brand' => 'Baseus',
                'price' => 55.00,
                'oldPrice' => 69.00,
                'image' => 'https://image.alza.cz/products/BASEf104/BASEf104.jpg?width=500&height=500',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 30,
                'monthlyPrice' => null,
                'description' => 'Prémiumový kovový telenko s 65W Power Delivery na rýchle nabíjanie laptopov a digitálnym displejom stavu.',
                'specs' => [
                    'Capacity' => '20000mAh',
                    'Output' => '65W PD Max',
                    'Body' => 'Metal Casing',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 20
            ],
            [
                'id' => 33,
                'title' => 'Anker Nano Power Bank',
                'brand' => 'Anker',
                'price' => 35.00,
                'oldPrice' => 45.00,
                'image' => 'https://image.alza.cz/products/Anker22a01/Anker22a01.jpg?width=500&height=500',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 60,
                'monthlyPrice' => null,
                'description' => 'Kompaktné a prenosné riešenie s integrovaným USB-C konektorom na priame nabíjanie smartfón.',
                'specs' => [
                    'Capacity' => '5000mAh',
                    'Output' => '22.5W Max',
                    'Connector' => 'Integrated USB-C',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 22
            ],
            [
                'id' => 34,
                'title' => 'RAVPower 26800mAh PD',
                'brand' => 'RAVPower',
                'price' => 59.00,
                'oldPrice' => 79.00,
                'image' => 'https://www.bhphotovideo.com/images/fb/ravpower_65_02058_101_rp_pb058_26800mah_usb_c_1313332.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 25,
                'monthlyPrice' => null,
                'description' => 'Obrovská kapacita s 30W výstupom Power Delivery na rýchle napájanie laptopov a tabletov.',
                'specs' => [
                    'Capacity' => '26800mAh',
                    'Output' => '30W PD Max',
                    'Ports' => 'USB-C, 2x USB-A',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 25
            ],
            [
                'id' => 35,
                'title' => 'Belkin BoostCharge 10K',
                'brand' => 'Belkin',
                'price' => 25.00,
                'oldPrice' => 35.00,
                'image' => 'https://image.alza.cz/products/BE324a1/BE324a1-03.jpg?width=500&height=500',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'powerbanks',
                'stock' => 45,
                'monthlyPrice' => null,
                'description' => 'Tenký a prenosný power bank s 10000mAh s certifikovanými bezpečnostnými funkciami a 15W výstupom USB-C.',
                'specs' => [
                    'Capacity' => '10000mAh',
                    'Output' => '15W Max',
                    'Safety' => 'Certified Protection',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 28
            ],

            // SMARTFÓNY - SÉRIA 2
            [
                'id' => 36,
                'title' => 'iPhone 15 Pro Max',
                'brand' => 'Apple',
                'price' => 1199.00,
                'oldPrice' => 1299.00,
                'image' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcR06Vo2NNqhmZUDR59TD2rw9Jb6Oselqt3jUVQwGhxjxZg5F4n7vifLHLhNIh6eGIWdDGA-z27kPhm7Xx7zXjNEo5eNRy2Q_bM3G03WX07skJcp8BTFF_LytLc',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 8,
                'monthlyPrice' => '29,95',
                'description' => 'Väčší 6,7" displej s 5x optickým zoomom a čipom A17 Pro v odolnom titánovom dizajne.',
                'specs' => [
                    'Display' => '6.7" Super Retina XDR',
                    'Processor' => 'A17 Pro chip',
                    'RAM' => '8GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '48MP Main, 12MP 5x Zoom',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'TOP 5',
                'discount_type' => 'percent',
                'discount_value' => 7
            ],
            [
                'id' => 37,
                'title' => 'Samsung Galaxy Z Fold 5',
                'brand' => 'Samsung',
                'price' => 1599.00,
                'oldPrice' => 1799.00,
                'image' => 'https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcResMntygmPasOEE0LW6kvTu8-VjmaylUpF-evnL2nBPiLa5jH5Gg4engeZo4OETLwz3nCMslpHP2UMV2hKK-skbmc0PuAWNcQ6MZdwx-yBuWY2jb9IBOLs2g',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 5,
                'monthlyPrice' => '39,95',
                'description' => 'Revolučné skladateľné zariadenie s 7,6" hlavným displejom na ponory a pokročilenú multitasking.',
                'specs' => [
                    'Display' => '7.6" Dynamic AMOLED 2X',
                    'Processor' => 'Snapdragon 8 Gen 2 for Galaxy',
                    'RAM' => '12GB',
                    'Storage' => '256GB, 512GB, 1TB',
                    'Camera' => '50MP Triple Camera',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],
            [
                'id' => 38,
                'title' => 'Google Pixel 8',
                'brand' => 'Google',
                'price' => 699.00,
                'oldPrice' => 799.00,
                'image' => 'https://doc.smarty.sk/pic/KW20000L01-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 15,
                'monthlyPrice' => '17,45',
                'description' => 'Inteligentný a kompaktný s nádherným displejom 6,2" Actua a pokročilými funkciami Google AI kamery.',
                'specs' => [
                    'Display' => '6.2" Actua OLED',
                    'Processor' => 'Google Tensor G3',
                    'RAM' => '8GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '50MP Main, 12MP Ultra-Wide',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 12
            ],
            [
                'id' => 39,
                'title' => 'OnePlus 11 5G',
                'brand' => 'OnePlus',
                'price' => 599.00,
                'oldPrice' => 699.00,
                'image' => 'https://doc.smarty.sk/pic/WLHM300401-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 12,
                'monthlyPrice' => '14,95',
                'description' => 'Flagship výkon s Snapdragon 8 Gen 2, 120Hz AMOLED a ultra-rýchle 100W nabíjanie.',
                'specs' => [
                    'Display' => '6.7" AMOLED, 120Hz',
                    'Processor' => 'Snapdragon 8 Gen 2',
                    'RAM' => '8GB, 16GB',
                    'Storage' => '128GB, 256GB',
                    'Camera' => '50MP Main Hasselblad',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 40,
                'title' => 'Xiaomi 13T Pro',
                'brand' => 'Xiaomi',
                'price' => 549.00,
                'oldPrice' => 649.00,
                'image' => 'https://doc.smarty.sk/pic/JMZ7G00101-600-600.webp',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 18,
                'monthlyPrice' => '13,70',
                'description' => 'Skvelý 144Hz CrystalRes AMOLED a profesionálna kamera Leica s ultra-rýchlym 120W HyperCharge.',
                'specs' => [
                    'Display' => '6.67" CrystalRes AMOLED, 144Hz',
                    'Processor' => 'Dimensity 9200+',
                    'RAM' => '12GB',
                    'Storage' => '512GB',
                    'Camera' => '50MP Main Leica',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 41,
                'title' => 'Motorola Edge 40 Pro',
                'brand' => 'Motorola',
                'price' => 599.00,
                'oldPrice' => 699.00,
                'image' => 'https://img-cdn.heureka.group/v1/6743b4f0-f7ab-4fa0-af3b-6574c5fa623d.jpg?width=2000&height=2000&fit=upsize',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 20,
                'monthlyPrice' => '14,95',
                'description' => 'Plynulý 165Hz pOLED displej a ultra-rýchle 125W TurboPower nabíjanie na čistej skúsenosti Android.',
                'specs' => [
                    'Display' => '6.67" pOLED, 165Hz',
                    'Processor' => 'Snapdragon 8 Gen 2',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Camera' => '50MP Triple Camera',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 42,
                'title' => 'Nothing Phone (2)',
                'brand' => 'Nothing',
                'price' => 529.00,
                'oldPrice' => 599.00,
                'image' => 'https://cdn.myshoptet.com/usr/www.hellocomp.cz/user/shop/big/10847-1_71x5ntu43-l.jpg?696f7810',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'phones',
                'stock' => 14,
                'monthlyPrice' => '13,20',
                'description' => 'Jedinečné rozhranie Glyph a transparentný dizajn s úžasným displejom 6,7" LTPO OLED.',
                'specs' => [
                    'Display' => '6.7" LTPO OLED, 120Hz',
                    'Processor' => 'Snapdragon 8+ Gen 1',
                    'RAM' => '12GB',
                    'Storage' => '256GB',
                    'Interface' => 'Glyph Interface',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 11
            ],

            // SLÚCHADLÁ
            [
                'id' => 43,
                'title' => 'Sony WH-1000XM5',
                'brand' => 'Sony',
                'price' => 299.00,
                'oldPrice' => 349.00,
                'image' => 'https://image.nay.sk/foto/500/2/6/3/product_5045362.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 25,
                'monthlyPrice' => '7,45',
                'description' => 'Vedúce v priemysle potlačenie hluku a výnimočná kvalita zvuku pre nadradenú skúsenosť s poslúchaniu.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'ANC' => 'Industry-leading',
                    'Battery' => '30 hours with ANC',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => 'TOP 6',
                'discount_type' => 'percent',
                'discount_value' => 14
            ],
            [
                'id' => 44,
                'title' => 'Bose QuietComfort Ultra',
                'brand' => 'Bose',
                'price' => 399.00,
                'oldPrice' => 429.00,
                'image' => 'https://www.l-e.sk/media/catalog/product/cache/5bfac8feb3d826c49ca6a9bcdd127146/1/7/1757346292_1919545.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 18,
                'monthlyPrice' => '9,95',
                'description' => 'Svetového typu potlačenie hluku a prelomové ponorné zvuku pre návratné zvukové skúsenosti.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Audio' => 'Immersive Audio',
                    'ANC' => 'World-class',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 7
            ],
            [
                'id' => 45,
                'title' => 'Apple AirPods Max',
                'brand' => 'Apple',
                'price' => 499.00,
                'oldPrice' => 549.00,
                'image' => 'https://www.l-e.sk/media/catalog/product/cache/5bfac8feb3d826c49ca6a9bcdd127146/b/o/bowers___wilkins_px8_s2_2.png',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 12,
                'monthlyPrice' => '12,45',
                'description' => 'Zvuk vysokej vernosti kombinovaný s vedúcim v priemysle aktívnym potlačením hluku a luxusným dizajnom.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Chip' => 'Apple H1 (x2)',
                    'Audio' => 'Spatial Audio',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 9
            ],
            [
                'id' => 46,
                'title' => 'Sennheiser Momentum 4 Wireless',
                'brand' => 'Sennheiser',
                'price' => 279.00,
                'oldPrice' => 329.00,
                'image' => 'https://www.l-e.sk/media/catalog/product/cache/5bfac8feb3d826c49ca6a9bcdd127146/m/o/momentum-wireless-4.jpg',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 20,
                'monthlyPrice' => '6,95',
                'description' => 'Výnimočná kvalita zvuku a adaptívne potlačenie hluku s neuveriteľnou 60-hodinovou výdržou batérie.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Battery' => '60 hours',
                    'Audio' => 'Signature Sound',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 15
            ],
            [
                'id' => 47,
                'title' => 'JBL Tune 770NC',
                'brand' => 'JBL',
                'price' => 99.00,
                'oldPrice' => 119.00,
                'image' => 'https://mc-static.fast.eu/pics/35/35059297/35059297-twoeighty.webp?1786534625',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 35,
                'monthlyPrice' => null,
                'description' => 'Výkonný zvuk JBL Pure Bass s aktívnym potlačením hluku a výdržou batérie až 70 hodín.',
                'specs' => [
                    'Type' => 'Over-ear, Wireless',
                    'Audio' => 'Pure Bass Sound',
                    'Battery' => '70 hours',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 16
            ],
            [
                'id' => 48,
                'title' => 'Samsung Galaxy Buds2 Pro',
                'brand' => 'Samsung',
                'price' => 179.00,
                'oldPrice' => 229.00,
                'image' => 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQkbUgadPjYpDt7c58Y5keAECJqcKvFY6-UX9zR5x6OpRXsx30QYny7t2JA42UBAaq1PMxSjG37poc4nLDfNylYJ2iRcTpoJVF3FKiQRI6B',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 40,
                'monthlyPrice' => null,
                'description' => 'Ponorný 24-bitový zvuk Hi-Fi a inteligentné aktívne potlačenie hluku v pohodlnom dizajne.',
                'specs' => [
                    'Type' => 'True Wireless',
                    'Audio' => '24-bit Hi-Fi',
                    'ANC' => 'Intelligent',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 21
            ],
            [
                'id' => 49,
                'title' => 'Nothing Ear (2)',
                'brand' => 'Nothing',
                'price' => 129.00,
                'oldPrice' => 149.00,
                'image' => 'https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcT5Cr2Ptxa-pyzHcdGO-ygXnrrLsvN4pMM9diADoI5PLwEYV_V0JlnuuJLfOxAxbSFKGVDKe_AuVlRFsu6yVDDOPQCCAGNejgv1P-gkAqA',
                'rating' => 0,
                'reviews' => 0,
                'category' => 'sluchadla',
                'stock' => 30,
                'monthlyPrice' => null,
                'description' => 'Transparentný dizajn s personalizovaným ANC a zvukom Hi-Res pre čistú zvukovú skúsenosť.',
                'specs' => [
                    'Type' => 'True Wireless',
                    'Audio' => 'Hi-Res, LHDC 5.0',
                    'Design' => 'Transparent',
                ],
                'service' => 'Do polnoci objednáš, ráno v Doma máš!',
                'topBadge' => null,
                'discount_type' => 'percent',
                'discount_value' => 13
            ],
        ];

        foreach ($products as $productData) {
            // Convert specs array to formatted text
            if (is_array($productData['specs'])) {
                $specsText = [];
                foreach ($productData['specs'] as $key => $value) {
                    $specsText[] = "$key: $value";
                }
                $productData['specs'] = implode("\n", $specsText);
            }
            Product::create($productData);
        }
    }
}